server.port=8081
spring.application.name=ai-mcp-client

# GCP Gemini Model
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-1.5-flash

# Pointing to ai-mcp-sandbox using Server-Sent Events (SSE)
spring.ai.mcp.client.sse.connections.ecom-server.url=${MCP_SERVER_URL:http://ai-mcp-sandbox-service:8080}