apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: aliaz333/admin-server:latest
          ports:
            - containerPort: 8087
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: LoadBalancer
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087