spring.application.name=admin-server
server.port=8087

# Register with Eureka so Admin Server can discover all microservices
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
# Force Eureka to use IP address instead of hostname
eureka.instance.prefer-ip-address=true