spring.application.name=eureka-server

# Default port for Eureka Server
server.port=8761

# Tell Eureka Server NOT to register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Wait time for subsequent sync
eureka.server.wait-time-in-ms-when-sync-empty=0

eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans