spring.application.name=eureka-server

# Default port for Eureka Server
server.port=8761

# Tell Eureka Server NOT to register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Wait time for subsequent sync
eureka.server.wait-time-in-ms-when-sync-empty=0
