spring.application.name=product-service
server.port=8082

# ==========================================
# MYSQL DATABASE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/product_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:test}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# AWS S3 CONFIGURATION
# ==========================================
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME:your-ecommerce-bucket-name}
aws.s3.region=${AWS_REGION:ap-south-1}
aws.credentials.access-key=${AWS_ACCESS_KEY_ID:YOUR_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:YOUR_SECRET_KEY}

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# EUREKA & SPRING BOOT ADMIN REGISTRATION
# ==========================================
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/

# Allows Spring Boot Admin server to find and display this service details via Eureka
spring.boot.admin.client.instance.service-url=http://product-service:8082
spring.boot.admin.client.url=http://spring-boot-admin-service:8087

# ==========================================
# OBSERVABILITY & MANAGEMENT (Required for Admin Server UI)
# ==========================================
management.server.port=8082
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.prometheus.metrics.export.enabled=true