name: API Gateway Pipeline
on:
  push:
    branches: [ main ]
    paths: [ 'api-gateway/**' ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: api-gateway
    secrets: inherit