name: Auth Service Pipeline
on:
  push:
    branches: [ main ]
    paths: [ 'authservice/**' ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: authservice
    secrets: inherit