name: Cart Service Pipeline
on:
  push:
    branches: [ main ]
    paths: [ 'cart-service/**' ]
jobs:
  deploy:
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: cart-service
    secrets: inherit