name: 3. Microservices Smart Deploy

on:
  workflow_run:
    workflows: ["2. Deploy DevOps Tools"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - 'authservice/**'
      - 'cart-service/**'
      - 'order-service/**'
      - 'payment-service/**'
      - 'product-service/**'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    outputs:
      changed_services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for modified files (Skips services that have no changes)
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api-gateway: 'api-gateway/**'
            authservice: 'authservice/**'
            cart-service: 'cart-service/**'
            order-service: 'order-service/**'
            payment-service: 'payment-service/**'
            product-service: 'product-service/**'

  deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed_services != '[]' && needs.detect-changes.outputs.changed_services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service_name: ${{ fromJSON(needs.detect-changes.outputs.changed_services) }}
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: ${{ matrix.service_name }}
    secrets: inherit