name: Order Service Pipeline
on:
  push:
    branches: [ main ]
    paths: [ 'order-service/**' ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: order-service
    secrets: inherit