name: Payment Service Pipeline
on:
  push:
    branches: [ main ]
    paths: [ 'payment-service/**' ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      service_name: payment-service
    secrets: inherit