name: Infrastructure Provisioning (Terraform)

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region ap-south-1 --name ecommerce-cluster

      - name: Install Kafka and Prometheus in Cloud EKS
        run: |
          # Add Helm repositories
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          # Install Kafka sequentially for t3.micro stability
          helm upgrade --install kafka bitnami/kafka \
            --set replicaCount=1 \
            --set auth.clientProtocol=none \
            --set listeners.client.protocol=PLAINTEXT \
            --timeout 10m

          # Install Prometheus & Grafana
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --set grafana.service.type=LoadBalancer \
            --timeout 10m